DROP TABLE IF EXISTS INVESTOR;
 
CREATE TABLE INVESTOR(
  INVSTR_ID INT PRIMARY KEY,
  INVSTR_NAME VARCHAR(250) NOT NULL,
  CLIENT_ID INT NOT NULL,
  CONSTRAINY FK_INVSTR FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT(CLIENT_ID));

INSERT INTO INVESTOR(INVSTR_ID , INVSTR_NAME ,CLIENT_ID) VALUES
  (1001, 'GLOBAL GOLD', 100),
  (2001, 'SAPHIRE INC.',100),
  (3001, 'PROSPERITY INC.', 200);
  (4001, 'VENUS CAPITAL', 200);
  (5001, 'ACE INC.', 200);
  (6001, 'CORE PROPERTIES', 300); 
  (7001, 'INFINITY WEALTH MGMT GROUP', 300);